language: c
sudo: enabled
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install -y gcc-7
script:
  - CC=gcc-7 make build
notifications:
  email: false
